sudo: required
language: csharp
services:  
  #Enable docker service inside travis
  - docker
mono:
  - latest
before_install:  
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"  
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
  - dnu restore
script:
  - dnx -p test/ExampleTests/project.json test 
  - docker build -t poolieweb/thehuntui .
  - docker tag poolieweb/thehuntui:latest poolieweb/thehuntui:v1
  - docker push poolieweb/thehuntui