language: CSharp
services:  
  #Enable docker service inside travis
  - docker
before_install:  
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
  - dnu restore
script:
  - dnx -p test/ExampleTests/project.json test 
  #build the image
  - docker build --no-cache -t poolieweb/thehuntui .
  #tag the build
  - docker tag  poolieweb/thehuntuilatest  poolieweb/thehuntui:v1
  #push the image to the repository
  - docker push  poolieweb/thehuntui